# Makefile for mock ML project

# Make predictions
predict:
	python src/predict.py

# Preprocess data
preprocess:
	python src/preprocess.py

# Biild docker-image
build-docker:
	docker build -t mock_ml_image .
